# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
workflows:
  version: 2
  test-and-publish:
    jobs:
    # Always build
    - build:
        filters:
          tags:
            # Build version tags in addition to normal branches
            only: /^v.*/
    - publish:
        requires:
        # Build before publishing
        - build
        filters:
          tags:
            # Only publish version tags
            only: /^v.*/
          branches:
            # Don't publish any branches
            ignore: /.*/
jobs:
  build:
    docker:
    - image: projectstorm/ci
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - modules-{{ checksum "package.json" }}
    - run: yarn || yarn || yarn
    - run: greenkeeper-lockfile-update
    - save_cache:
        paths:
        - node_modules
        key: modules-{{ checksum "package.json" }}
    - run: yarn run build:ts:prod
    - run:
        name: Unit Test
        command: yarn test:ci
        environment:
          JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
    - store_test_results:
        path: reports/junit
    - store_artifacts:
        path: coverage
    - run:
        name: Code Coverage
        command: codecov
    - run: greenkeeper-lockfile-upload

  publish:
    docker:
    - image: projectstorm/ci
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - modules-{{ checksum "package.json" }}
    - run:
        name: Setup NPM
        command: |
          echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
    - run: yarn || yarn || yarn
    - run:
        name: Publish
        command: |
          if [[ "$CIRCLE_TAG" =~ ^v[0-9]*\.[0-9]*\.[0-9]*$ ]]; then
            echo "Release $CIRCLE_TAG"
            npm publish --unsafe-perm
          else
            echo "Prerelease $CIRCLE_TAG"
            npm publish --tag next
          fi